apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-test
  namespace: 11lxf-uat
  labels:
    app: vue-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-test
  template:
    metadata:
      name: vue-test
      labels:
        app: vue-test
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: vue-test
          image: dockerhub.shawf.me/11lxf/vue-test:1.0.0
          # 测试环境tag一样，每次都拉取最新的镜像
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
            requests:
              cpu: '50m'
              memory: '128Mi'
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: PUID
              value: "3000"
            - name: PGID
              value: "3000"
          volumeMounts:
            - name: logs-data
              mountPath: /var/log/nginx
              subPath: vue-test
      restartPolicy: Always
      volumes:
        - name: logs-data
          persistentVolumeClaim:
            claimName: logs-claim
