apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: vue-test

images:
  - name: dockerhub.shawf.me/11lxf/vue-test
    newName: dockerhub.shawf.me/11lxf/${SERVICE_NAME}
    newTag: ${VERSION}
