apiVersion: v1
kind: Service
metadata:
  name: vue-test
  namespace: 11lxf-uat
  labels:
    app: vue-test
spec:
  type: ClusterIP
  selector:
    app: vue-test
  ports:
    - name: vue-http
      port: 80
      targetPort: 80
