apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - http-route.yaml

namespace: 11lxf-uat

configMapGenerator:
  - name: nginx-config
    files:
      - conf/cover-nginx-conf.conf

patchesStrategicMerge:
  - patches/patch-deployment.yaml